-- MySQL Script generated by MySQL Workbench
-- Sun May 25 19:56:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema upwayz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `upwayz` ;

-- -----------------------------------------------------
-- Schema upwayz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upwayz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `upwayz` ;

-- -----------------------------------------------------
-- Table `upwayz`.`entradaestoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upwayz`.`entradaestoque` ;

CREATE TABLE IF NOT EXISTS `upwayz`.`entradaestoque` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `data_entrada` DATE NOT NULL,
  PRIMARY KEY (`id_entrada`),
  CONSTRAINT `entradaestoque_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `upwayz`.`produto` (`id_produto`),
  CONSTRAINT `entradaestoque_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `upwayz`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `upwayz`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upwayz`.`produto` ;

CREATE TABLE IF NOT EXISTS `upwayz`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `tamanho` VARCHAR(10) NULL DEFAULT NULL,
  `cor` VARCHAR(30) NULL DEFAULT NULL,
  `preco_custo` DECIMAL(10,2) NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `upwayz`.`saidaestoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upwayz`.`saidaestoque` ;

CREATE TABLE IF NOT EXISTS `upwayz`.`saidaestoque` (
  `id_saida` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `data_saida` DATE NOT NULL,
  PRIMARY KEY (`id_saida`),
  CONSTRAINT `saidaestoque_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `upwayz`.`produto` (`id_produto`),
  CONSTRAINT `saidaestoque_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `upwayz`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `upwayz`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upwayz`.`usuario` ;

CREATE TABLE IF NOT EXISTS `upwayz`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
